apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ngmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ngmy
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ngmy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ngmy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ngmy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-zifc-tenant/appstudio/dc-metro-map-ngmy@sha256:1736bae9c6f56464ab204482d41027d35e5ab2939483439f06725f73d4116dbb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
